### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [joshwget/tc359-project18#1]
I think you probably forgot to `git push origin master`, because this still looks like last week's project. Also, the Heroku app just seems to load forever and then time out, so you may need to repush there as well.

**Comment by joshwget** [comment]
Oops, accidently pushed to the wrong repo! I'm not actually having any problems with the Heroku app though. Can you try it now and see if it's still having problems?

**Comment by chrisvfritz** [comment]
Much better! And the Heroku app is working as well now. Not sure what was happening before. :confused: Either way, everything looks good except that [this line](https://github.com/joshwget/tc359-project18/blob/master/app/models/movie.rb#L3) is actually redundant:

``` ruby
validates :favorite, length: { minimum: 1 }
```

Since we're already validating the presence of `:favorite` and anything with a zero length is considered blank and therefore not present, this validation is automatically implied, so can be deleted.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by joshwget** [comment]
Should be fixed! Sorry, I had forgotten this issue.

**Comment by chrisvfritz** [comment]
:+1:
